site_name: TiDB for AI
site_url: https://pingcap.github.io/ai
repo_name: pingcap/tidb
repo_url: https://github.com/pingcap/tidb
edit_uri: https://github.com/pingcap/pingcap.github.io/tree/main/src
docs_dir: src
watch:
  - src

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.ico
  color_mode: dark
  palette:
    # Palette toggle for dark mode
    - scheme: tidb-dark
      primary: custom
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: tidb-light
      primary: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  features:
    - content.code.copy
    - content.tabs.link
    - content.action.edit
    - content.tooltips
    - toc.follow
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.tracking
    - navigation.instant
    - content.footnote.tooltips
  icon:
    repo: fontawesome/brands/github
    annotation: material/arrow-right-circle

plugins:
  - search
  # - autorefs
  # - mkdocs-jupyter
  - redirects:
      redirect_maps:
        "index.md": "ai/index.md"
        "ai/integrations/mcp.md": "ai/integrations/tidb-mcp-server.md"

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: ..
      dedent_subsections: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - md_in_html
  - abbr
  - attr_list
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - markdown.extensions.toc:
      baselevel: 1
      permalink: ""
  - pymdownx.arithmatex:
      generic: true

nav:
  - Home:
    - TiDB for AI: ai/index.md
    - ðŸš€ Quickstart: ai/quickstart.md
    - ðŸ“– Concepts:
      - Vector Search: ai/concepts/vector-search.md
    - ðŸ“š Guides:
      - Connect to database: ai/guides/connect.md
      - Working with tables: ai/guides/tables.md
      - Vector Search: ai/guides/vector-search.md
      - Fulltext Search: ai/guides/fulltext-search.md
      - Hybrid Search: ai/guides/hybrid-search.md
      - Auto Embedding: ai/guides/auto-embedding.md
      - Reranking: ai/guides/reranking.md
      - Filtering: ai/guides/filtering.md
    - ðŸ’¡ Demos:
      - Gallery: ai/examples/index.md
      - Basic Usage: ai/examples/basic-with-pytidb.md
      - Auto Embedding: ai/examples/auto-embedding-with-pytidb.md
      - Vector Search: ai/examples/vector-search-with-pytidb.md
      - Fulltext Search: ai/examples/fulltext-search-with-pytidb.md
      - Hybrid Search: ai/examples/hybrid-search-with-pytidb.md
      - Image Search: ai/examples/image-search-with-pytidb.md
      - RAG: ai/examples/rag-with-pytidb.md
      - Memory: ai/examples/memory-with-pytidb.md
      - Text2SQL: ai/examples/text2sql-with-pytidb.md
    - ðŸ”Œ Integrations:
      - MCP Integration:
        - TiDB MCP Server: ai/integrations/tidb-mcp-server.md
      - IDE & Tool Integration:
        - Cursor: ai/integrations/tidb-mcp-cursor.md
        - Claude Desktop: ai/integrations/tidb-mcp-claude-desktop.md
      - LlamaIndex: ai/integrations/llamaindex.md
      - LangChain: ai/integrations/langchain.md
  - Concepts:
    - Vector Search: ai/concepts/vector-search.md
  - Guides:
    - Connect to database: ai/guides/connect.md
    - Working with tables: ai/guides/tables.md
    - Vector Search: ai/guides/vector-search.md
    - Fulltext Search: ai/guides/fulltext-search.md
    - Hybrid Search: ai/guides/hybrid-search.md
    - Auto Embedding: ai/guides/auto-embedding.md
    - Reranking: ai/guides/reranking.md
    - Filtering: ai/guides/filtering.md
    - Transaction: ai/guides/transaction.md
    - Raw Queries: ai/guides/raw-queries.md
    - Multiple Table Joins: ai/guides/joins.md
  - Demos:
    - Gallery: ai/examples/index.md
    - Basic Usage: ai/examples/basic-with-pytidb.md
    - Auto Embedding: ai/examples/auto-embedding-with-pytidb.md
    - Vector Search: ai/examples/vector-search-with-pytidb.md
    - Fulltext Search: ai/examples/fulltext-search-with-pytidb.md
    - Hybrid Search: ai/examples/hybrid-search-with-pytidb.md
    - Image Search: ai/examples/image-search-with-pytidb.md
    - RAG: ai/examples/rag-with-pytidb.md
    - Memory: ai/examples/memory-with-pytidb.md
    - Text2SQL: ai/examples/text2sql-with-pytidb.md
  - Integrations:
    - MCP Integration:
      - TiDB MCP Server: ai/integrations/tidb-mcp-server.md
    - IDE & Tool Integration:
      - Cursor: ai/integrations/tidb-mcp-cursor.md
      - Claude Desktop: ai/integrations/tidb-mcp-claude-desktop.md
    - LlamaIndex: ai/integrations/llamaindex.md
    - LangChain: ai/integrations/langchain.md


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pingcap/pytidb
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/TiDB_Developer
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/pingcap

extra_css:
  - styles/extra.css

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
